In [1]:
#numpy
#create array

import numpy as np

#1d array
my_list = [1,2,3,4]
my_array1 = np.array(my_list, dtype='complex')

print(my_array1)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [2]:
my_array1

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [3]:
my_list

[1, 2, 3, 4]

In [4]:
#2d array

my_list1 = [1,3,2],[7,8,9],[4,5,6]

my_array2 = np.array(my_list1)



my_array2.sort()
print(my_array2)



[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [5]:
#shape n size
print('shape:',my_array2.shape)
print('Datatype:',my_array2.dtype)
print('size:',my_array2.size)
print('num dimension:',my_array2.ndim)

shape: (3, 3)
Datatype: int32
size: 9
num dimension: 2


In [6]:
#extract from array

print(my_array2[ :2, :2])

[[1 2]
 [7 8]]


In [7]:
b= my_array2 > 3

my_array2[b]


array([7, 8, 9, 4, 5, 6])

In [8]:
b

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [9]:
#reverse rows

#row positions only

my_array2[ : :-1, ]

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [10]:
#column reverse

my_array2[ : :-1, : :-1 ]


array([[6, 5, 4],
       [9, 8, 7],
       [3, 2, 1]])

In [11]:
my_array2


array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [12]:
#mean , max , min 

print('Mean value is',my_array2.mean())
print('Max value is',my_array2.max())
print('Min value is',my_array2.min())



Mean value is 5.0
Max value is 9
Min value is 1


In [15]:
#reshape

my_array2.reshape(3,3)

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [16]:
a= my_array2

In [17]:
a

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [18]:
#flatten

my_array2.flatten()

array([1, 2, 3, 7, 8, 9, 4, 5, 6])

In [19]:
#seq reps , random no

print(np.arange(8))
print(np.arange(1,10))
print(np.arange(0,30,3))
print(np.arange(10,1,-2))


[0 1 2 3 4 5 6 7]
[1 2 3 4 5 6 7 8 9]
[ 0  3  6  9 12 15 18 21 24 27]
[10  8  6  4  2]


In [20]:
np.insert(my_array2,3,[3,4,5])

array([1, 2, 3, 3, 4, 5, 7, 8, 9, 4, 5, 6])

In [21]:
my_array2

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [22]:
np.linspace(1,50,10)  #dtype float

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [23]:
np.ones([4,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.linspace(1,50,10,dtype=int)  #dtype int

array([ 1,  6, 11, 17, 22, 28, 33, 39, 44, 50])

In [26]:
# random no

print(np.random.rand(2,2))

[[0.62771763 0.85815674]
 [0.09923987 0.85690049]]


In [27]:
#for int

print(np.random.randint(0,10,size =[2,3]))

[[1 0 3]
 [3 1 7]]
